name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)

env:
  CI: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
          - rubylang/ruby:master-nightly-bionic
        gemfile:
          - rails-6.0
          - rails-6.1
          - rails-7.0
        test_framework:
          - rspec
          - rake
        include:
          - ruby: rubylang/ruby:master-nightly-bionic
            allow_failures: "true"
    env:
      BUNDLE_WITHOUT: 'development'
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Cache vendor/bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ matrix.ruby }}-${{ github.sha }}
          restore-keys: |
            v1-gem-${{ runner.os }}-${{ matrix.ruby }}-
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - name: bundle update
        run: |
          set -xe
          bundle config path vendor/bundle
          bundle update --jobs $(nproc) --retry 3
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - name: Run ${{ matrix.test_framework }}
        run: |
          set -xe
          bundle exec ${{ matrix.test_framework }}
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
